# Generated by Django 5.1.7 on 2025-05-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_feedback_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='User_name',
            new_name='Name',
        ),
    ]
